src/Entity/Support.php
<?php

namespace App\Entity;

use App\Repository\SupportRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SupportRepository::class)]
class Support
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_sortie = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'supports')]
    private ?Editor $constructeur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDeSortie(): ?\DateTimeInterface
    {
        return $this->date_de_sortie;
    }

    public function setDateDeSortie(\DateTimeInterface $date_de_sortie): self
    {
        $this->date_de_sortie = $date_de_sortie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getConstructeur(): ?Editor
    {
        return $this->constructeur;
    }

    public function setConstructeur(?Editor $constructeur): self
    {
        $this->constructeur = $constructeur;

        return $this;
    }
}

src/Form/SupportType.php
<?php

namespace App\Form;

use App\Entity\Support;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SupportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_de_sortie')
            ->add('description')
            ->add('constructeur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Support::class,
        ]);
    }
}

src/Controller/SupportController.php
<?php

namespace App\Controller;

use App\Entity\Support;
use App\Form\SupportType;
use App\Repository\SupportRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/support')]
class SupportController extends AbstractController
{
    #[Route('/', name: 'app_support_index', methods: ['GET'])]
    #[IsGranted("ROLE_ADMIN")]
    public function index(SupportRepository $supportRepository): Response
    {
        return $this->render('support/index.html.twig', [
            'supports' => $supportRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_support_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SupportRepository $supportRepository): Response
    {
        $support = new Support();
        $form = $this->createForm(SupportType::class, $support);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $supportRepository->save($support, true);

            return $this->redirectToRoute('app_support_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('support/new.html.twig', [
            'support' => $support,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_support_show', methods: ['GET'])]
    public function show(Support $support): Response
    {
        return $this->render('support/show.html.twig', [
            'support' => $support,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_support_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Support $support, SupportRepository $supportRepository): Response
    {
        $form = $this->createForm(SupportType::class, $support);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $supportRepository->save($support, true);

            return $this->redirectToRoute('app_support_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('support/edit.html.twig', [
            'support' => $support,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_support_delete', methods: ['POST'])]
    public function delete(Request $request, Support $support, SupportRepository $supportRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$support->getId(), $request->request->get('_token'))) {
            $supportRepository->remove($support, true);
        }

        return $this->redirectToRoute('app_support_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/support/_delete_form.html.twig
<form method="post" action="{{ path('app_support_delete', {'id': support.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ support.id) }}">
    <button class="btn">Delete</button>
</form>

templates/support/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/support/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Support{% endblock %}

{% block body %}
    <h1>Edit Support</h1>

    {{ include('support/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_support_index') }}">back to list</a>

    {{ include('support/_delete_form.html.twig') }}
{% endblock %}

templates/support/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Support index{% endblock %}

{% block body %}
    <h1>Support index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_de_sortie</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for support in supports %}
            <tr>
                <td>{{ support.id }}</td>
                <td>{{ support.nom }}</td>
                <td>{{ support.dateDeSortie ? support.dateDeSortie|date('Y-m-d') : '' }}</td>
                <td>{{ support.description }}</td>
                <td>
                    <a href="{{ path('app_support_show', {'id': support.id}) }}">show</a>
                    <a href="{{ path('app_support_edit', {'id': support.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_support_new') }}">Create new</a>
{% endblock %}

templates/support/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Support{% endblock %}

{% block body %}
    <h1>Create new Support</h1>

    {{ include('support/_form.html.twig') }}

    <a href="{{ path('app_support_index') }}">back to list</a>
{% endblock %}

templates/support/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Support{% endblock %}

{% block body %}
    <h1>Support</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ support.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ support.nom }}</td>
            </tr>
            <tr>
                <th>Date_de_sortie</th>
                <td>{{ support.dateDeSortie ? support.dateDeSortie|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ support.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_support_index') }}">back to list</a>

    <a href="{{ path('app_support_edit', {'id': support.id}) }}">edit</a>

    {{ include('support/_delete_form.html.twig') }}
{% endblock %}