src/Entity/Games.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\GamesRepository;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: GamesRepository::class)]
class Games
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $bool = false;

    #[ORM\ManyToOne(inversedBy: 'games')]
    #[ORM\JoinColumn(onDelete: "SET NULL")]
    private ?Editor $editor = null;

/*     #[ORM\Column(type: Types::DATE_IMMUTABLE)] */
    private ?\DateTime $releaseDate;

    #[ORM\OneToOne(cascade: ['persist', 'remove'], orphanRemoval: true)]
    private ?Image $mainImage = null;

    private bool $deleteMainImage;

    #[ORM\ManyToOne(inversedBy: 'games')]
    private ?User $author = null;

    public function __construct()
    {
        $this->releaseDate = new \DateTime;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isBool(): ?bool
    {
        return $this->bool;
    }

    public function setBool(bool $bool): self
    {
        $this->bool = $bool;

        return $this;
    }

    public function getEditor(): ?Editor
    {
        return $this->editor;
    }

    public function setEditor(?Editor $editor): self
    {
        $this->editor = $editor;

        return $this;
    }
    public function getReleaseDate(): ?\DateTime
    {
        return $this->releaseDate ?? new \DateTime;
    }
    public function setReleaseDate(?\DateTime $releaseDate): self
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    public function getMainImage(): ?Image
    {
        return $this->mainImage;
    }

    public function setMainImage(?Image $mainImage): self
    {
        if ($mainImage !== null && $mainImage->getPath() !== null) {
            $this->mainImage = $mainImage;
        }

        return $this;
    }

    public function getDeleteMainImage(): bool
    {
        return $this->deleteMainImage;
    }

    public function setDeleteMainImage(?bool $deleteMainImage): self
    {
        $this->deleteMainImage = $deleteMainImage;

        if ($this->deleteMainImage) {
            $this->mainImage = null;
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
// Indique à Doctrine que cette entitée posséde des événements (cycle de vie)
#[ORM\HasLifecycleCallbacks]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    #[ORM\Column(length: 80)]
    private ?string $name = null;

    #[Assert\Image(maxSize: '10M')]
    private UploadedFile $file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    private string $oldPath = "";

    public function getFile(): UploadedFile
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file): self
    {
        $this->file = $file;
        $this->oldPath = $this->path ?? '';
        $this->path = ''; // on vide le path pour que Doctrine puisse comprendre que le prochain path est pas pareil

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function generatePath(): self
    {
        // Si un fichier a bien été envoyé
        if ($this->file instanceof UploadedFile) {
            // Génére un chemin
            $this->path = uniqid("img_").'.'.$this->file->guessExtension();
            $this->name = $this->file->getClientOriginalName();
        }

        return $this;
    }

    /**
     * Retourne le lien absolu vers le dossier d'upload (DIRECTORY_SEPARATOR choisi selon l'OS le / ou \ du lien du fichier)
     */
    public static function getPublicRootDir(): string
    {
        return __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.
        'public'.DIRECTORY_SEPARATOR.'uploads'.DIRECTORY_SEPARATOR;
    }

    #[ORM\PostPersist]
    #[ORM\PostUpdate]
    public function upload(): void
    {
        if (is_file(self::getPublicRootDir().$this->oldPath)) {
            unlink(self::getPublicRootDir().$this->oldPath);
        }

        if ($this->file instanceof UploadedFile) {
            $this->file->move(self::getPublicRootDir(), $this->path);
        }
    }

    public function getWebPath(): string
    {
        return '/uploads/'. $this->path;
    }

    #[ORM\PreRemove]
    public function removeFile(): void
    {
        if (is_file(self::getPublicRootDir().$this->path)) {
            unlink(self::getPublicRootDir().$this->path);
        }
    }
}

src/Form/GamesType.php
<?php

    namespace App\Form;

use App\Entity\Games;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;

    class GamesType extends AbstractType{

        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('title', null, [
                    'label' => 'tableAdmin.title',
                    'help' => 'tableAdmin.title_help',
                ])
                ->add('editor', null, [
                    'label' => 'tableAdmin.editor',
                    'query_builder' => function (EntityRepository $er){
                        return $er->createQueryBuilder('e')
                        ->orderBy('e.name', 'ASC');
                    }
                ])

                ->add('releaseDate', DateType::class, [
                    'label' => 'tableAdmin.releaseDate',
                    'years' => range(1972,date("Y")),
                ])

                ->add('bool', ChoiceType::class, [
                    'label' => 'tableAdmin.enabled',
                    'choices' => [
                        'no' => false,
                        'yes' => true,
                    ],
                    'expanded' => true,
                ])
                ->add('description', null, [
                    'label' => 'tableAdmin.description',
                    'attr' => [
                        'row' => 10,
                    ]
                ])

                ->add('mainImage', ImageType::class, [
                    'label' => 'tableAdmin.Image'
                ])

                ->add('deleteMainImage', CheckboxType::class, [
                    'label' => 'tableAdmin.delete_main_image',
                    'required' => false
                ])

            ;
        }


        public function configureOptions(OptionsResolver $resolver): void
        {
            // indique que ce formulaire va traiter les données d'objet de type Games
            $resolver->setDefaults([
                'data_class' => Games::class,
            ]);
        }
    }

?>

src/Controller/GamesController.php
<?php

namespace App\Controller;

use App\Entity\Games;
use App\Form\GamesType;
use App\Repository\GamesRepository;
use App\Security\Voter\GamesVoter;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Contracts\Translation\TranslatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/games', name: 'app_games')]


class GamesController extends AbstractController
{

    #[Route('/new', name: 'app_new')]
    #[IsGranted("ROLE_USER")]
    public function new(EntityManagerInterface $em, Request $request, TranslatorInterface $translator): Response
    {
        // $newGames = new Games;
        // $newGames->setTitle("Super Titre");
        // $newGames->setbool(true);

        // $em->persist($newGames); //prépare la requête d'ajouter
        // $em->flush(); //execute

        // Nouveau version du code

        $entity = new Games;
        $entity->setAuthor($this->getUser());
        // Création d'un formulaire, et envoyer dans $entity
        $form = $this->createForm(GamesType::class, $entity);

        // Cherche des données _POST pour les envoyer au formulaire
        $form->handleRequest($request);

        // Test form
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($entity);
            $em->flush();

            //Ajout de message temporaire, addFlash est une fonction de symfony, qui indique le nom du message, puis le contenu
            $this->addFlash('success', $translator->trans('games.new.success', [
                '%title%' => $entity->getTitle(),
            ]));

            return $this->redirectToRoute('app_gamesapp_admin');
        }

        return $this->render('games/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/admin', name: 'app_admin')]
    #[IsGranted("ROLE_USER")]
    public function admin(GamesRepository $gamesRepository, Request $request): Response
    {
        $author = $this->getUser();

        if ($this->isGranted('ROLE_USER')) {
            $author = null;
        }

        $p = $request->get('p', 1); // Page 1 par defaut
        $itemCount = 5;
        $search = $request->get('s', '');

        $entities = $gamesRepository->findData($itemCount, $p, $search);

        $pageCount = ceil($entities->count() / $itemCount);

        return $this->render('games/admin.html.twig', [
            'entities' => $entities,
            'pageCount' => max($pageCount, 1),
        ]);
    }

    /**
     * Route avec un parmettre "id"
     * 
     * regex "\d+" d signifi uniquement nombre et le + veut dire 1 ou plus
     * 
     * @Route("/{id}/edit", requirements={"id": "\d+"})
     */
    #[IsGranted("ROLE_USER")]
    public function edit(EntityManagerInterface $em, Request $request, Games $entity, TranslatorInterface $translator): Response{
        
        $this->denyAccessUnlessGranted(GamesVoter::EDIT, $entity);

        
        if ($entity->getAuthor() === null) {
            $entity->setAuthor($this->getUser());
        }
        
        $form = $this->createForm(GamesType::class, $entity);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            $this->addFlash('warning', $translator->trans('games.edit.success', [
                '%title%' => $entity->getTitle(),
            ]));

            return $this->redirectToRoute('app_gamesapp_admin');
        }

        return $this->render('games/edit.html.twig',[
            'form' => $form->createView(),
            'entity' => $entity,
        ]);
    }

    /**
     * @Route("/{id}/delete", requirements={"id": "\d+"})
     */
    public function delete(EntityManagerInterface $em, Request $request, Games $entity, TranslatorInterface $translator): Response{

        if ($this->isCsrfTokenValid('delete_games_'.$entity->getId(), $request->get('token'))) {
            $em->remove($entity);
            $em->flush();
            $this->addFlash('danger', $translator->trans('games.delete.success', [
                '%title%' => $entity->getTitle(),
            ]));

            return $this->redirectToRoute('app_gamesapp_admin');
        }

        return $this->render('games/delete.html.twig', [
            'entity' => $entity,
        ]);
    }
}

templates/games/admin.html.twig
{% extends 'back.layout.html.twig' %}

{% block content %}

	<h1>{{ 'games.title'|trans }}</h1>

	{# div>table.table>thead>tr>th*3 #}

	<div class="card">
		<div class="card-header">
			<a href="{{ path('app_gamesapp_new') }}" class"btn btn-success">{{ 'games.new.title'|trans }}</a>
		</div>
	</div>
	<div class="card-body">
		<form action="" method="get" class="d-flex my-3">
			<input type="text" name="s" class="form-control" value="{{ app.request.get('s') }}"/>
			<button type="submit" class="btn btn-light ms-1">Rechercher</button>
		</form>
		<div class="table-responsive">
			<table class="table">
				<thead>
					<tr>
						<th>{{ 'tableAdmin.title'|trans }}</th>
						<th>{{ 'tableAdmin.editor'|trans }}</th>
						<th>{{ 'tableAdmin.releaseDate'|trans }}</th>
						<th>{{ 'tableAdmin.activate'|trans }}</th>
						<th>{{ 'tableAdmin.actions'|trans }}</th>
					</tr>
				</thead>

				<tbody>
					{% for entity in entities %}
						<tr>
							<td>
								{% if entity.mainImage is not empty %}
									<img src="{{ asset(entity.mainImage.webPath) }}" alt="">
								{% endif %}
							</td>
							<td>{{ entity.title }}</td>
							<td>{{ entity.editor }}</td>
							<td>{{ entity.releaseDate|date("M Y") }}</td>
							<td class="text-white {{ entity.bool ? 'bg-success' : 'bg-warning' }}">{{ entity.bool ? 'Oui' : 'Non' }}</td>
							<td>
								<a href="{{ path('app_gamesapp_games_edit', {"id": entity.id}) }}" class="btn btn-light">Modifier</a>

								<a href="{{ path('app_gamesapp_games_delete', {"id": entity.id}) }}" class="btn btn-danger">Supprimer</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="card-footer">
			<div class="d-flex justify-content-between align-items-center">
				{% include "decorator/_pagination.html.twig" with {"route": "app_gamesapp_admin"} %}

				<div>{{ entities.count }}
					jeux</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/games/delete.html.twig
{% extends 'back.layout.html.twig' %}

{% block content %}

    <h1>Supprimer un jeu</h1>

    <form action="" method="post">
        <h1>{{ 'games.delete.confirm'|trans({'%title%': entity.title}) }}</h1>

        <a href="{{ path('app_gamesapp_admin') }}" class="btn btn-light">Non, annuler</a>
        <button type="submit" class="btn btn-danger">Oui supprimer</button>

        <input type="hidden" name="token" value="{{ csrf_token('delete_games_' ~ entity.id) }}" />
    </form>

{% endblock %}

templates/games/edit.html.twig
{% extends 'back.layout.html.twig' %}

{% block content %}

    <h1>Modifier le jeu "{{ entity.title }}"</h1>

{{ form_start(form) }}
{{ form_errors(form) }}
    <div class="card">
        <div class="card-body">
            {# {{ form_widget(form) }} #}

            <div class="row">
                <div class="col-md-8">
                    {{ form_row(form.title) }}
                    {{ form_row(form.releaseDate) }}
                    {{ form_row(form.description) }}
                </div>

                <div class="col-md-4">
                    {{ form_row(form.bool) }}
                    {{ form_row(form.editor) }}
                </div>
            </div>

            <div class="d-flex justify-content-between">
                {% if entity.mainImage is not empty %}
                    <img src="{{ asset(entity.mainImage.webPath) }}" alt="">
                {% endif %}

                <div class="flex-grow-1">
                    {{ form_row(form.mainImage.file) }}
                    {{ form_row(form.deleteMainImage) }}
                </div>
            </div>


        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
    </div>
{{ form_end(form) }}
{% endblock %}

templates/games/new.html.twig
{% extends 'back.layout.html.twig' %}

{% block content %}

    {# <h1>Hello word!</h1> #}
    

{% endblock %}